name: 测试跨账号发布

on:
  workflow_dispatch:

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      # 1. 生成文本文件
      - name: 生成文本文件
        run: |
          echo "触发时间: $(date)" >> release-1.0.0.ipa

      # 2. 生成日志文件
      - name: 生成日志文件
        run: |
          echo "运行ID: ${{ github.run_id }}" >>release-1.0.0.apk


      # 3. 跨账号发布
      - name: 创建版本并上传
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.WY_SECRET }}
          repository: "wy15828318331/2025part"
          tag_name: test-${{ github.run_id }}
          name: "1.0.0"
          files: |
            *.ipa
            *.apk
